// What each room needs and gives, in a player's words — the source of the "You need" block in the room guide.
// Keyed by room display name. Edit here; both docs read it.
export const ROOM_NEEDS: Record<string, string> = {
  "My Workspace": "Take the mug. You leave with: mug. Type: `get mug`, `out`. `read report` for the setup. `publish` publishes to yourself; while Publish to web is on in the Sacristy, publishing to the internet is \u2620.",
  "Village Square": "Read the prophecy (+5); quiet Jeff. Bring: mug (My Workspace). Type: `read board`, `give mug to jeff`. `n` Mill, `e` Refresh Fields, `s` OneLake Shore, `u` Town Hall, `in` My Workspace. `show me a table` starts Jeff's Excel.",
  "Town Hall": "Nothing scores. The Clerk says where the admins are. Bring: ticket (here). Type: `talk to clerk` \u00d74, `get ticket`, `give ticket to clerk`. Everything is an admin setting. `d` back to the square.",
  "Dataflow Gen1 Mill": "Get the Gen1 credentials (+10). You leave with: credentials. Type: `talk to miller` (or `open chest`, `get credentials`).",
  "Refresh Fields": "Pass through, east to the Foothills. Type: Never `refresh` here (\u2620).",
  "Foothills": "The crossroads: north to the Keep, east up the Peaks. Type: `n` Power BI Desktop Gate; `e` Throttling Pass.",
  "Power BI Desktop Gate": "Click the Try free link (+10): the guard wants a SKU and the trial is free. You leave with: bridge down. Type: `use trial`, then `n`. `say trial` only gets you 'Show me.' Don't `swim moat` (\u2620).",
  "Power Query Hall": "Pass through. Optional: rebuild the query in order (+10 bonus). Type: `source` \u00b7 `navigate` \u00b7 `promote headers` \u00b7 `change type` \u00b7 `filter rows` \u00b7 `remove other columns` \u00b7 `rename columns`. `look at steps`. `n` Duke, `w` Model View, `e` Report Studio. Don't type DAX into the M editor (\u2620).",
  "Duke's Chamber": "Hand the Duke your date table (+20): unmarked or CALENDARAUTO, either way you are thrown into the Moat of T-SQL and land at the Gate. Bring: date table (Model View). You leave with: Trial 2: you smell like a Warehouse (`trial.moat`). Type: `give date table to duke`. `say calculated column` is a strike now; three strikes and you are a column (curse).",
  "The Model View": "Activate the dashed Date-to-Sales line (+10), then take the date table. North is the back gate to the Monastery. You leave with: date table. Type: `use relationship`, `get date table`, later `n`. Don't turn on bidirectional filtering (\u2620).",
  "The Report Studio": "Put a measure on the Card, twice (+10: the first one never counts); change the pie to a bar chart (+15) and the Big Refresh finishes. You leave with: boots (wear them). Type: `put measure on card` \u00b7 `put measure on card`; `change pie chart to bar chart`; `wear boots`. Don't `open other page` (\u2620). Don't stare past six (the Blank curse).",
  "Monastery Gate": "Press Start on the Spark session (+5). You leave with: gate open. Type: `start session`, then `n`. `wait` only bills.",
  "Cloister": "Get the Hoodie of Spark (+15) once the notebook runs; optional errand. Bring: notebook fixed (Spark Session Chamber). You leave with: hoodie (wear it: Trial 1). Type: `talk to abbot`, `wear hoodie`. `talk to abbot` again for the errand (+10 bonus). `w` Library, `e` Spark Chamber, `u` Sacristy, `s` Gate.",
  "Library of Deprecated Notebooks": "Trade your license for the PySpark scroll (+10); read it (+5). Bring: license (you start with it). You leave with: scroll. Type: `give license to librarian`, `read scroll`.",
  "Spark Session Chamber": "Fix Brother Pandas' notebook (+20). Bring: scroll (Library). You leave with: notebook fixed. Type: `use scroll on notebook` (or `give scroll to pandas`).",
  "The Sacristy": "Optional: flip tenant and capacity settings; put them back (+5); turn off Publish to web for the Abbot (+10). Type: `settings`, `read <book>`, `turn off <book>`, `turn on <book>`, `reset settings`. `turn on block public internet` and `pause capacity` are \u2620. `d` back.",
  "OneLake Shore": "The lake crossroads. Type: `e` Ferryman's Dock, `s` the marshes, `w` The Lake House, `n` the square. Don't `import the lake` (\u2620).",
  "Ferryman's Dock": "Bring the Ferryman online (+15). Bring: credentials (Mill). You leave with: ferry online. Type: `give credentials to ferryman`, `board boat`.",
  "Isle of Gateway": "Take the standard key (+20), not the personal one. You leave with: standard key (Trial 3). Type: `get standard key`, `board boat`.",
  "The Lake House": "Nothing; the room is the joke. Type: `e` back to the Shore.",
  "Bronze Marsh": "Pass through south. Drink nothing. Type: `s`. `drink` is \u2620.",
  "Silver Marsh": "Pass through south. Type: `s`.",
  "Gold Marsh": "Take the shortcut (+10); it takes you home. You leave with: shortcut. Type: `get shortcut`, `use shortcut` (back to the Shore, from anywhere).",
  "Throttling Pass": "Pass through north (boots help). Bring: boots (Report Studio). Type: `n`. Don't drink the CapacityAde (\u2620).",
  "Bursting Ledge": "The door opens for the Worthy Three (+5). Bring: hoodie worn (Cloister), the moat smell (Duke's Chamber), standard key (Isle of Gateway). You leave with: Shrine open. Type: `n` (or `open door`).",
  "The Shrine": "Answer the dragon (+10); take the model (+5, the win). You leave with: the Golden Semantic Model. Type: `say star schema`, `get model`. `attack dragon` is \u2620.",
  "Sheet1": "Get Jeff's goal; show him the pivot (+20 bonus). Bring: the finished pivot (PivotTable1). Type: `ask jeff`, later `show jeff`. `n` Data tab, `e` PivotTable1, `out` leaves.",
  "The Data tab": "Connect to the certified model. Bring: your license (or its library receipt). You leave with: a connection. Type: `use analyze in excel`, `sign in`. `s` Sheet1.",
  "PivotTable1": "Build the pivot. Bring: the connection (Data tab). You leave with: a finished pivot. Type: `create pivot table`, `use sales region`, `use net sales`, `filter by year`. `w` Sheet1.",
  "The Copilot Pane": "Get Copilot to one number (+25 bonus). Bring: the names (Model Gallery). Type: `total q4 2025 northeast net sales from the certified model, just the number`, or one slot at a time. `e` Gallery, `out` leaves.",
  "The Model Gallery": "Read the certified model's name and measures. You leave with: the words Copilot wants. Type: `look at certified`. `w` back to the Pane.",
};
